---
ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

infrastructure:
  - changed-files:
    - any-glob-to-any-file:
      - terraform/**

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - docs/**
      - guides/**
      - README.md
      - ./*.md

app-basics:
  - changed-files:
    - src/app/*

app-core:
  - changed-files:
    - src/app/core/*

app-shared:
  - changed-files:
    - src/app/shared/*
...
