---
ci-cd:
  - '.github/**'

infrastructure:
  - 'terraform/**'

documentation:
  - ['docs/**', 'guides/**', 'README.md', '**/*.md']

app-basics:
  - 'src/app/*'

app-core:
  - 'src/app/core/*'

app-shared:
  - 'src/app/shared/*'

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']
...
