---
ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

infrastructure:
  - changed-files:
    - any-glob-to-any-file: 'terraform/**'

documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/**', 'guides/**', 'README.md', '**/*.md']

app-basics:
  - changed-files: 
    - any-glob-to-any-file: 'src/app/*'

app-core:
  - changed-files:
    - any-glob-to-any-file: 'src/app/core/*'

app-shared:
  - changed-files:
    - any-glob-to-any-file: 'src/app/shared/*'

feat:
  - head-branch: ['^feat']

fix:
  - head-branch: ['^fix']

docs:
  - head-branch: ['^docs']

misc:
  - head-branch: ['^chore', '^build', '^test', '^ops', '^refactor', '^perf', '^style']

...
